class Vec3d {
private:
  const	double x,y,z;
public:
	Vec3d(double x = 0, double y = 0, double z = 0) : x(x), y(y), z(z) {
	}
#if 0
	~Vec3d() {

	}
	// not needed, this is generated by default
	Vec3d(const Vec3d& orig) : x(orig.x), y(orig.y), z(orig.z) {
	}

	Vec3d& operator =(const Vec3d& orig) {
		x = orig.x;
		y = orig.y;
		z = orig.z;
		return *this;
	}
#endif
};

int main() {
	Vec3d a(1,2,3);
	Vec3d b(1);
	Vec3d c(1,2);
	Vec3d d(c); // generated automatically, no need to write
	int x = 2, y = 3, z = 4;
	x = y = z = 0;
	a = b; // generated automatically
	
	a = b = c;
	if (a == b)
		;
}
